# fly.toml app configuration file generated for telegrambot-njfz7w on 2026-08-06T23:58:23Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'telegrambot-njfz7w'
primary_region = 'iad'

[build]

[env]

[processes]
  app = 'python telegram_bot_raw.py'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
